modLoader="javafml" #mandatory
loaderVersion="[25,)" #mandatory (24 is current forge version)
[[mods]] #mandatory
modId="custom_painting" #mandatory
version="0.0" #mandatory
displayName="Custom Paintings Mod" #mandatory
description='''
DESCRIPTION
'''
